<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Pembayaran DP | Al Fazza Kost</title>@vite(['resources/css/app.css', 'resources/css/style.css', 'resources/js/app.js'])</head>
<body class="initial-payment-page">
@php($isDp = $pembayaran->jenis_pembayaran === 'DP')
<nav class="initial-payment-nav"><a href="{{ route('landing') }}" class="initial-payment-brand">Al Fazza Kost</a><x-back-button href="{{ route('booking.status', $pembayaran->booking) }}" aria-label="Kembali ke status booking" /></nav>
<main class="initial-payment-wrap"><header class="initial-payment-heading"><span class="initial-payment-tag">Pembayaran Awal</span><h1>{{ $isDp ? 'Pembayaran DP' : $pembayaran->jenis_pembayaran }}</h1><p>Selesaikan pembayaran awal untuk melanjutkan proses menjadi penghuni Al Fazza Kost.</p></header>
@if($errors->any())<div class="initial-payment-alert initial-payment-alert-error" role="alert"><strong>Pembayaran belum dapat diproses.</strong><span>{{ $errors->first() }}</span></div>@endif
<section class="initial-payment-card"><div class="initial-payment-card-title"><div><span class="initial-payment-eyebrow">Ringkasan booking</span><h2>Booking #{{ $pembayaran->booking->id_booking }}</h2></div><span class="initial-payment-status">{{ $pembayaran->booking->status_booking }}</span></div><div class="initial-payment-details"><div><span>Kode Booking</span><strong>#{{ $pembayaran->booking->id_booking }}</strong></div><div><span>Nama Pemesan</span><strong>{{ $pembayaran->booking->nama_pemesan }}</strong></div><div><span>Nomor WhatsApp</span><strong>{{ $pembayaran->booking->no_whatsapp }}</strong></div><div><span>Nomor Kamar</span><strong>Kamar {{ $pembayaran->booking->kamar->nomor_kamar ?? '-' }}</strong></div><div><span>Lokasi Kost</span><strong>{{ $pembayaran->booking->kamar->lokasi_kos ?? '-' }}</strong></div><div><span>Total {{ $isDp ? 'DP' : 'Pembayaran' }}</span><strong>Rp {{ number_format($pembayaran->jumlah_bayar, 0, ',', '.') }}</strong></div></div></section>
@if($pembayaran->metode_bayar && $pembayaran->status_bayar !== 'Ditolak')
<section class="initial-payment-card initial-payment-result"><div class="initial-payment-result-icon">⏳</div><div><h2>{{ $pembayaran->gateway_provider === 'DANA' && $pembayaran->gateway_status === 'PENDING' ? 'Menunggu Konfirmasi DANA' : 'Menunggu Validasi Admin' }}</h2><p>{{ $pembayaran->gateway_provider === 'DANA' && $pembayaran->gateway_status === 'PENDING' ? 'Selesaikan pembayaran di halaman resmi DANA. Status tidak berubah hanya karena Anda kembali ke halaman ini.' : 'Pembayaran telah dikirim dan menunggu pemeriksaan Admin.' }}</p></div></section>
@else
<section class="initial-payment-card"><div class="initial-payment-card-title"><div><span class="initial-payment-eyebrow">{{ $isDp ? 'DP Booking' : $pembayaran->jenis_pembayaran }}</span><h2>Rp {{ number_format($pembayaran->jumlah_bayar, 0, ',', '.') }}</h2></div><span class="initial-payment-dp">{{ $isDp ? 'DP' : 'Sewa' }}</span></div><p class="initial-payment-intro">Pilih metode pembayaran yang paling nyaman untuk Anda.</p>
<form method="POST" enctype="multipart/form-data" action="{{ route('pembayaran.awal.proses', $pembayaran) }}" data-payment-form>@csrf
<fieldset class="initial-payment-methods"><legend>Metode Pembayaran</legend>
<label class="initial-payment-method" data-method="Transfer"><input type="radio" name="metode_bayar" value="Transfer" {{ old('metode_bayar') === 'Transfer' ? 'checked' : '' }} required><span class="initial-payment-method-icon">🏦</span><span><strong>Transfer Bank</strong><small>Pembayaran melalui rekening Al Fazza Kost</small></span><span class="initial-payment-radio"></span></label>
<label class="initial-payment-method" data-method="QRIS"><input type="radio" name="metode_bayar" value="QRIS" {{ old('metode_bayar') === 'QRIS' ? 'checked' : '' }} required><span class="initial-payment-method-icon">▣</span><span><strong>QRIS</strong><small>Scan QRIS untuk melakukan pembayaran</small></span><span class="initial-payment-radio"></span></label>
<label class="initial-payment-method" data-method="Cash"><input type="radio" name="metode_bayar" value="Cash" {{ old('metode_bayar') === 'Cash' ? 'checked' : '' }} required><span class="initial-payment-method-icon">💵</span><span><strong>Cash/Tunai</strong><small>Pembayaran tunai langsung kepada pihak Al Fazza Kost</small></span><span class="initial-payment-radio"></span></label></fieldset>
<div class="initial-payment-instruction" data-instruction="Transfer" hidden><strong>Rekening Transfer</strong>@if(filled($bank['name']) && filled($bank['account_number']) && filled($bank['account_name']))<p>{{ $bank['name'] }} · No. Rekening <b>{{ $bank['account_number'] }}</b><br>Atas Nama: <b>{{ $bank['account_name'] }}</b></p>@else<p><b>Informasi rekening belum dikonfigurasi.</b> Hubungi Admin Al Fazza Kost untuk memperoleh rekening transfer resmi.</p>@endif</div>
<div class="initial-payment-instruction initial-payment-qris" data-instruction="QRIS" hidden><strong>QRIS Al Fazza Kost</strong>@if($qrisSetting?->qris_path)<img src="{{ asset('storage/' . $qrisSetting->qris_path) }}" alt="QRIS Al Fazza Kost"><p>Scan QRIS, lalu unggah bukti pembayaran.</p>@else<p><b>QRIS belum tersedia.</b> Silakan gunakan metode lain atau hubungi Admin.</p>@endif</div>
<div class="initial-payment-instruction" data-instruction="Cash" hidden><strong>Pembayaran Tunai</strong><p>Bayarkan DP langsung kepada pihak Al Fazza Kost. Pembayaran tetap Pending sampai divalidasi Admin.</p></div>
<div class="initial-payment-proof" data-proof hidden><label for="bukti_bayar">Upload Bukti Pembayaran</label><input id="bukti_bayar" type="file" name="bukti_bayar" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"><small>Format JPG, JPEG, PNG, atau WEBP. Ukuran maksimum 2 MB.</small></div><p class="initial-payment-note" data-payment-note>Pembayaran akan diperiksa dan divalidasi oleh Admin.</p><button type="submit" class="initial-payment-submit" data-submit-label>Lanjutkan Pembayaran</button></form></section>
@endif</main>
<script>document.querySelectorAll('[data-payment-form]').forEach(form=>{const proof=form.querySelector('[data-proof]'),proofInput=proof?.querySelector('input'),button=form.querySelector('[data-submit-label]');const select=method=>{form.querySelectorAll('.initial-payment-method').forEach(card=>card.classList.toggle('is-selected',card.dataset.method===method));form.querySelectorAll('[data-instruction]').forEach(item=>item.hidden=item.dataset.instruction!==method);proof.hidden=method==='Cash';proofInput.required=['Transfer','QRIS'].includes(method);button.textContent='Kirim untuk Verifikasi';};form.querySelectorAll('input[name="metode_bayar"]').forEach(input=>input.addEventListener('change',()=>select(input.value)));const selected=form.querySelector('input[name="metode_bayar"]:checked');if(selected)select(selected.value);form.addEventListener('submit',()=>{button.disabled=true;button.textContent='Mengirim pembayaran...';});});</script>
</body></html>
